--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AID-LEARNING/libExtraPath
branches:
  - master
  - pm5
projects:
  libConverterNBT:
    path: ""
    type: library
    model: virion
...
